<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_BookAnAppointment
 * @copyright   Copyright (c) 2023 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

/** @var $block \M2Commerce\BookAnAppointment\Block\AppointmentBlock */
/** @var $productViewBlock \Magento\Catalog\Block\Product\View */
/** @var $escaper \Magento\Framework\Escaper */

$productViewBlock= $block->getLayout()->createBlock('Magento\Catalog\Block\Product\View');
$product = $productViewBlock->getProduct();
?>

<?php if($product->getBookAppointment()): ?>
    <a href="#" id="click-appointment" data-role="book-appointment" class="action book-appointment">
        <span><?= $block->escapeHtml(__('Book an Appointment')) ?></span>
    </a>
    <div id="book-appointment-popup" class="book-appointment-modal" style="display: none;">
        <div class="appointment-msg-div">
        </div>
        <form class="form contact" action="<?= $escaper->escapeUrl($block->getFormAction()) ?>" id="appointment-book-form" method="post"
              data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $escaper->escapeHtml(__('Book An Appointment')) ?></span></legend><br />
                <div class="field name required">
                    <label class="label" for="name"><span><?= $escaper->escapeHtml(__('Name:')) ?></span></label>
                    <div class="control">
                        <input name="name" id="name" title="<?= $escaper->escapeHtmlAttr(__('Name:')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $escaper->escapeHtml(__('Email:')) ?></span></label>
                    <div class="control">
                        <input name="email" id="email" title="<?= $escaper->escapeHtmlAttr(__('Email:')) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="field telephone required">
                    <label class="label" for="telephone"><span><?= $escaper->escapeHtml(__('Phone Number:')) ?></span></label>
                    <div class="control">
                        <input name="telephone" id="telephone" title="<?= $escaper->escapeHtmlAttr(__('Phone Number:')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field comment required">
                    <label class="label" for="comment"><span><?= $escaper->escapeHtml(__('Details:')) ?></span></label>
                    <div class="control">
                        <textarea name="comment" id="comment" title="<?= $escaper->escapeHtmlAttr(__('Details:')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
                    </div>
                </div>
                <?= $block->getChildHtml('form.additional.info') ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value="" />
                    <button id="book-apnt-btn" type="submit" title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                        <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <script type="text/x-magento-init">
        {
            "#click-appointment": {
                "appointmentJs": {}
            }
        }
    </script>
<?php endif; ?>
